blank_issues_enabled: false
contact_links:
  - name: Issue Tracker
    url: https://github.com/esphome/issues
    about: Please create bug reports in the dedicated issue tracker.
  - name: Frequently Asked Question
    url: https://esphome.io/guides/faq.html
    about: Please view the FAQ for common questions and what to include in a bug report.
